name: Node.js Push Pipeline

on:
  push:
    branches:
      - "**" # Runs on all branches except main

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  BuildAndUnitTestApp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.3.0 

      - name: Install Dependencies
        run: npm install  # Installs dependencies

      - name: Ensure Jest is Installed
        run: npm install --save-dev jest

      - name: Run Unit Tests
        run: npx jest # Runs unit tests